#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScoutingFRC.Resource", IsApplication=true)]

namespace ScoutingFRC
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.2.0.155")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int fuel = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int gear = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int light_blue = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int splash_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colors = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fuelButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int gearButton = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int modeSwitch = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int ModeSwitchThumb = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int ModeSwitchTrack = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int RCS_Logo_small = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int splash_screen = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int undoSmall = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int autoCompleteTextView1 = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int button1 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int buttonAdd = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int buttonCancel = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int buttonCollect = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int buttonGearGoal = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int buttonGearMiss = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int buttonHighGoal = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int buttonHighMiss = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int buttonLowGoal = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int buttonLowMiss = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int buttonPitScouting = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int buttonSubmit = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int buttonSubmitPit = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int buttonSync = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int buttonUndoGears = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int buttonUndoHighBoiler = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int buttonUndoLowBoiler = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int buttonView = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int checkBox1 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int checkBoxClimb = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int editTextMathcNumber = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int editTextNameP = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int editTextNotes = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int editTextNotesP = 2130903064;
			
			// aapt resource value: 0x7F03001A
			public const int editTextTeamNumber = 2130903066;
			
			// aapt resource value: 0x7F030019
			public const int editTextTeamNumP = 2130903065;
			
			// aapt resource value: 0x7F03001B
			public const int editTextYourName = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int linearLayout1 = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int linearLayout10 = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int linearLayout2 = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int linearLayout3 = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int linearLayout4 = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int linearLayout5 = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int linearLayout6 = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int linearLayout7 = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int linearLayout8 = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int linearLayout9 = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int linearLayoutAuto = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int linearLayoutListNotes = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int linearLayoutNotes = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int linearLayoutResults = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int linearLayoutTele = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int listView1 = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int listViewDevices = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int scrollView1 = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int switchAuto = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int textView1 = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int textView2 = 2130903088;
			
			// aapt resource value: 0x7F030031
			public const int textView3 = 2130903089;
			
			// aapt resource value: 0x7F030032
			public const int textView4 = 2130903090;
			
			// aapt resource value: 0x7F030033
			public const int textView5 = 2130903091;
			
			// aapt resource value: 0x7F030034
			public const int textView6 = 2130903092;
			
			// aapt resource value: 0x7F030035
			public const int textView7 = 2130903093;
			
			// aapt resource value: 0x7F030036
			public const int textViewAutoGear = 2130903094;
			
			// aapt resource value: 0x7F030037
			public const int textViewAutoGears = 2130903095;
			
			// aapt resource value: 0x7F030038
			public const int textViewAutoHG = 2130903096;
			
			// aapt resource value: 0x7F030039
			public const int textViewAutoHighBoiler = 2130903097;
			
			// aapt resource value: 0x7F03003A
			public const int textViewAutoLG = 2130903098;
			
			// aapt resource value: 0x7F03003B
			public const int textViewAutoLowBoiler = 2130903099;
			
			// aapt resource value: 0x7F03003C
			public const int textViewAutoPts = 2130903100;
			
			// aapt resource value: 0x7F03003D
			public const int textViewBaseline = 2130903101;
			
			// aapt resource value: 0x7F03003E
			public const int textViewClimbingView = 2130903102;
			
			// aapt resource value: 0x7F03003F
			public const int textViewReceived = 2130903103;
			
			// aapt resource value: 0x7F030040
			public const int textViewSent = 2130903104;
			
			// aapt resource value: 0x7F030041
			public const int textViewTeamNumber = 2130903105;
			
			// aapt resource value: 0x7F030042
			public const int textViewTeleGears = 2130903106;
			
			// aapt resource value: 0x7F030043
			public const int textViewTeleHG = 2130903107;
			
			// aapt resource value: 0x7F030044
			public const int textViewTeleHighBoiler = 2130903108;
			
			// aapt resource value: 0x7F030045
			public const int textViewTeleLG = 2130903109;
			
			// aapt resource value: 0x7F030046
			public const int textViewTeleLowBoiler = 2130903110;
			
			// aapt resource value: 0x7F030047
			public const int textViewTelePts = 2130903111;
			
			// aapt resource value: 0x7F030048
			public const int view1 = 2130903112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int DataCollection = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int PitScouting = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int SyncDevices = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ViewData = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060003
			public const int button_text = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int ct = 2131099652;
			
			// aapt resource value: 0x7F060000
			public const int CustomTheme = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int CustomTheme_Base = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int CustomTheme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
